make Docker Compose use PORT for --allow-net flag
Otherwise we get error like this:

error: Uncaught (in promise) PermissionDenied:
Requires net access to "0.0.0.0:8900", run again with the --allow-net flag

Signed-off-by: Jakub Sokołowski <jakub@status.im>